#!/bin/zsh

MOUNT_BASE="/home/han/USB"

notify() {
    notify-send "$1" "$2"
}

get_devices() {
    lsblk -rpno NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT \
        | awk '$3=="part" && $4!="" {print $1 " (" $2 ", " $4 ") " $5}'
}

mount_device() {
    local device="$1"
    local name
    local mount_point

    name="$(basename "$device")"
    mount_point="$MOUNT_BASE/$name"

    sudo mkdir -p "$mount_point"

    if mountpoint -q "$mount_point"; then
        notify "Mount" "$device is already mounted at $mount_point"
        exit 0
    fi

    fs_type="$(lsblk -no FSTYPE "$device")"

    case "$fs_type" in
        vfat|exfat|ntfs)
            sudo mount -o uid="$(id -u)",gid="$(id -g)" "$device" "$mount_point"
            ;;
        *)
            sudo mount "$device" "$mount_point"
            ;;
    esac

    if [ $? -eq 0 ]; then
        notify "Mount" "Mounted $device at $mount_point"
    else
        notify "Mount" "Failed to mount $device"
        rmdir "$mount_point" 2>/dev/null
    fi
}

get_mounted_usb() {
    lsblk -rpno NAME,MOUNTPOINT \
        | awk -v base="$MOUNT_BASE" '$2 ~ "^"base {print $1 " -> " $2}'
}

unmount_device() {
    local line="$1"
    local device
    local mount_point

    device="$(echo "$line" | awk '{print $1}')"
    mount_point="$(echo "$line" | awk '{print $3}')"

    sudo umount "$mount_point"

    if [ $? -eq 0 ]; then
        notify "Unmount" "Unmounted $device from $mount_point"
        rmdir "$mount_point" 2>/dev/null
    else
        notify "Unmount" "Failed to unmount $device"
    fi
}

action="$(printf "mount\nunmount" | dmenu -p "USB action:")"

case "$action" in
    mount)
        selected_device="$(
            get_devices |
            dmenu -l 10 -p "Select device to mount:" |
            awk '{print $1}'
        )"

        [ -n "$selected_device" ] && mount_device "$selected_device"
        ;;

    unmount)
        selected_mount="$(
            get_mounted_usb |
            dmenu -l 10 -p "Select device to unmount:"
        )"

        [ -n "$selected_mount" ] && unmount_device "$selected_mount"
        ;;

    *)
        notify "USB" "No valid action selected"
        ;;
esac

